x-accounting-depends-on: &accounting-depends-on
  db:
    condition: service_started
  migrator:
    condition: service_completed_successfully
x-accounting-migrator-depends-on: &accounting-migrator-depends-on
  db:
    condition: service_started
x-accounting-env-file: &accounting-env-file
  - ./docker/.env-dev

version: '3.9'

services:
  db:
    image: postgres:16.2
    container_name: accoutning_db
    restart: unless-stopped
    env_file: *accounting-env-file
    volumes:
      - db_home:/var/lib/postgresql/data

  migrator:
    image: registry.private.fffirer.top:9999/accounting-migrator:latest
    container_name: accounting_migrator
    env_file: *accounting-env-file
    depends_on: *accounting-migrator-depends-on
  
  app:
    image: registry.private.fffirer.top:9999/accounting:latest
    container_name: accounting_app
    env_file: *accounting-env-file
    ports:
      - "7865:8080"
    depends_on: *accounting-depends-on

volumes:
  db_home:
    external: false
