x-accounting-depends-on: &accounting-depends-on
  - db
  - migrator
x-accounting-env-file: &accounting-env-file
  - ./docker/.env-dev

version: '3.9'

services:
  db:
    image: postgres:16.2
    container_name: accoutning_db
    restart: unless-stopped
    env_file: *accounting-env-file
    volumes:
      - db_home:/var/lib/postgresql/data

  migrator:
    build: 
      context: .
      dockerfile: Migrator.Dockerfile
    container_name: accounting_migrator
    env_file: *accounting-env-file
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: accounting_app
    env_file: *accounting-env-file
    ports:
      - "7865:8080"
    depends_on: *accounting-depends-on

volumes:
  db_home:
    external: false
